<script>
    console.log('Task 1')
    try{
       console.log(z)
    }
    catch{
       console.log('Some Error Occurred and Handled...!')
    }
    finally{
       console.log('finally block executed')
    }
    console.log('Task 2')
   </script>
   